version: '3.7'

services:

  web:    
    build: .
    ports:
      - 8080:8080 # host:guest
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_RUN_PORT: 8080
      FLASK_RUN_HOST: 0.0.0.0
