version: '3.7'

services:

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - 8080:80
      - 8443:443
    volumes:
      # - ./nginx/www:/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  web:
    build: .
    # ports:
    #   - 8080:8080 # host:guest
    depends_on: 
      - nginx
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_RUN_PORT: 8080
      FLASK_RUN_HOST: 0.0.0.0
